### ISSUE TITLE
Unable to load valid module manifest data

### ISSUE THREAD

**Issue by githuberto** [shemetz/precise-drawing-tools#1]
Thanks for making this! I've been wanting something like this for months.

I'm unable to install the module from the module browser. It fails with:
```
Error: Unable to load valid module manifest data from "https://github.com/shemetz/precise-drawing-tools/releases/download/1.0.0/module.json"
The requested manifest at "https://github.com/shemetz/precise-drawing-tools/releases/download/1.0.0/module.json" did not provide module manifest data.
```
I *was* able to install it manually using `https://raw.githubusercontent.com/shemetz/precise-drawing-tools/master/module.json`.

**Comment by shemetz** [comment]
My bad, I didn't create a github release.  I think I fixed it now - can you try again? (uninstall and reinstall)

**Comment by githuberto** [comment]
Works like a charm, thanks!
