### ISSUE TITLE
Module not appearing in my activation list

### ISSUE THREAD

**Issue by hendelmasad** [shemetz/precise-drawing-tools#3]
Windows 10
Foundry version 9 Build 280
Hosted on Forge

Hello! I installed your module and I can't activate it because it doesn't appear in the Manage Modules list. Are there known conflicts?

**Comment by shemetz** [comment]
1. do you also have LibWrapper installed?  (it's a dependency)
2. do you see an error in the setup page, or in the console?

**Comment by hendelmasad** [comment]
I do have libWrapper installed and there are error messages but I think these are unrelated as I've seen them before. So far these errors haven't stopped anything from working, that I've noticed. I'll attach the log from the console if that will help.

I appreciate any insight you have.

Keith
[gmkeith-niburufx.forge-vtt.com-1666267551530.log](https://github.com/shemetz/precise-drawing-tools/files/9830385/gmkeith-niburufx.forge-vtt.com-1666267551530.log)

**Comment by hendelmasad** [comment]
I was able to get it to work on my local install which has very few modules. When I went back to my hosted games (on the Forge), I tried deactivating all modules except libWrapper but Precise Drawing still does not appear. I tried a few of my other games on the forge (both with modules on and off) and it still does not appear. Could it be the hosting service? The Forge?

Keith

**Comment by shemetz** [comment]
Can you try uninstalling and reinstalling the module?  I oddly enough had a similar issue but thought it was related to github.  If it becomes solved for you after you reinstall, it would mean I had the same problem.

**Comment by hendelmasad** [comment]
Just tried reinstalling it, still nothing. I've had modules activated and deactivated. I've created games under different game systems with all modules deactivated from the start to try to see if it would work, nothing unfortunately. On the stand alone client it works like a charm, on the Forge it doesn't.

**Comment by hendelmasad** [comment]
My Stand alone client is v10, and Forge hosting recommends v9, could that be it?

**Comment by shemetz** [comment]
Hmm, then it sounds like my module just has some instant manifest failure on V9 that does not appear on V10.

If you update to V10 the problem will disappear.  However, I do want to maintain compatibility for longer, so I'll need to figure out where I went wrong with backwards compatibility.

**Comment by hendelmasad** [comment]
Forge recommends v9 currently, so it'll be a while before I can update on the Forge. Hopefully not too much longer. One good thing from this whole issue, I've really trimmed the modules I have installed! LOL! I look forward to hearing what you find, in the interim I'll get by with the standard drawing tools.

Keith

**Comment by hendelmasad** [comment]
I upgraded to V10 Foundry and your module works like a charm, including on the hosting service, Forge. I figured it was time to upgrade anyways.  Thanks for the help.

K
