### ISSUE TITLE
[BUG] "Disabled Drag Resistance Feature" stops working after switching scenes

### ISSUE THREAD

**Issue by Asothin** [shemetz/precise-drawing-tools#8]
The feature works normally after first loading in, however it ceases to function upon switching to a different scene.

Precise Drawing Tool version:
Tested on 1.3.0 and 1.4.0

Foundry version tested:
Tested on 11.315 and 12.328

As the bug exists in Foundry v11 as well, backwards compatibility would be appreciated for game systems that haven't been updated to v12.

**Comment by shemetz** [comment]
Thanks for the report!

Fixed in v1.3.1 and v1.4.1
